### PR TITLE
Upgrade to bam-qc-metrics 0.2.3

### PR DESCRIPTION
**Pull request by iainrb**
- Change bam-qc-metrics version
- Increment workflow version
- Update changelog

### CODE REVIEW

**Comment by iainrb** [comment]
retest this please

**Comment by iainrb** [comment]
Running Jenkins to generate updated test outputs

**Comment by iainrb** [comment]
retest this please

**Comment by iainrb** [comment]
Ready for review.
No changes to decider, as the decider isn't running workflow version 3+.
Updated test data in /.mounts/labs/gsi/testdata/bamqc/output_expectation ; previous test data copied to /.mounts/labs/gsi/testdata/bamqc/output_expectation_v0.2.2

**Review by apmasell — APPROVED** [review]

**Review by mlaszloffy — APPROVED** [review]

**Pull request merged**
