### PR TITLE
Release 3.0: Picard MarkDuplicates and bam-qc-metrics

### PR DESCRIPTION
**Pull request by iainrb**
- Run Picard MarkDuplicates as part of workflow
- Change from old [bamqc](https://github.com/oicr-gsi/bamqc) Perl script to new [bam-qc-metrics](https://github.com/oicr-gsi/bam-qc-metrics) Python package
- Extensive changes to metrics: Some added/removed, all others reimplemented. See [bam-qc-metrics documentation](https://github.com/oicr-gsi/bam-qc-metrics/blob/master/metrics.md) for details.
- Modify downsampling parameters in the decider and workflow; new `sample_level` parameter determines target number of reads to downsample

### CODE REVIEW

**Comment by iainrb** [comment]
retest this please

**Comment by iainrb** [comment]
retest this please

**Comment by iainrb** [comment]
retest this please

**Comment by iainrb** [comment]
retest this please

**Comment by iainrb** [comment]
retest this please

**Review by mlaszloffy — APPROVED** [review]

**Review by xuemeiluo — APPROVED** [review]

**Pull request merged**
